# Generated by Django 4.2.3 on 2023-07-06 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('categoryId', models.AutoField(primary_key=True, serialize=False)),
                ('categoryName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('contractId', models.AutoField(primary_key=True, serialize=False)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('terms', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Credentials',
            fields=[
                ('credentialId', models.AutoField(primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderId', models.AutoField(primary_key=True, serialize=False)),
                ('orderDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='PointOfSale',
            fields=[
                ('posId', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=200)),
                ('cashierName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('telephone', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('creatDate', models.DateField()),
                ('updateDate', models.DateField()),
                ('contratId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mobileAppV1.contract')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('vehiculeId', models.AutoField(primary_key=True, serialize=False)),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('licensePlate', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('warehouseId', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=200)),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Moral',
            fields=[
                ('pointofsale_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='mobileAppV1.pointofsale')),
                ('moralId', models.AutoField(primary_key=True, serialize=False)),
                ('organizationName', models.CharField(max_length=100)),
            ],
            bases=('mobileAppV1.pointofsale',),
        ),
        migrations.CreateModel(
            name='Physical',
            fields=[
                ('pointofsale_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='mobileAppV1.pointofsale')),
                ('physicalId', models.AutoField(primary_key=True, serialize=False)),
                ('storeName', models.CharField(max_length=100)),
            ],
            bases=('mobileAppV1.pointofsale',),
        ),
        migrations.CreateModel(
            name='PreSeller',
            fields=[
                ('users_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='mobileAppV1.users')),
                ('preSellerId', models.AutoField(primary_key=True, serialize=False)),
                ('salesTarget', models.FloatField()),
                ('commissionRate', models.FloatField()),
            ],
            bases=('mobileAppV1.users',),
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('users_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='mobileAppV1.users')),
                ('sallerId', models.AutoField(primary_key=True, serialize=False)),
                ('salesRegion', models.CharField(max_length=100)),
            ],
            bases=('mobileAppV1.users',),
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('users_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='mobileAppV1.users')),
                ('supervisorId', models.AutoField(primary_key=True, serialize=False)),
                ('groupReference', models.CharField(max_length=100)),
                ('assigncRegion', models.CharField(max_length=100)),
                ('teamSize', models.IntegerField()),
                ('department', models.CharField(max_length=100)),
            ],
            bases=('mobileAppV1.users',),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productId', models.AutoField(primary_key=True, serialize=False)),
                ('productName', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categoryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobileAppV1.category')),
            ],
        ),
        migrations.CreateModel(
            name='OrderCard',
            fields=[
                ('orderCardId', models.AutoField(primary_key=True, serialize=False)),
                ('orderCardDate', models.DateField()),
                ('totalAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('orderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobileAppV1.order')),
                ('posId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobileAppV1.pointofsale')),
                ('vehiculeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobileAppV1.vehicule')),
            ],
        ),
        migrations.CreateModel(
            name='Storekeeper',
            fields=[
                ('users_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='mobileAppV1.users')),
                ('storekeeperId', models.AutoField(primary_key=True, serialize=False)),
                ('invertoryManagmentSystem', models.CharField(max_length=100)),
                ('warehouseLocation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mobileAppV1.warehouse')),
            ],
            bases=('mobileAppV1.users',),
        ),
        migrations.CreateModel(
            name='DeliveryGuy',
            fields=[
                ('users_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='mobileAppV1.users')),
                ('deliveryGuyId', models.AutoField(primary_key=True, serialize=False)),
                ('deliveryRoute', models.CharField(max_length=100)),
                ('vehiculeId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mobileAppV1.vehicule')),
            ],
            bases=('mobileAppV1.users',),
        ),
    ]
