# Generated by Django 4.2.3 on 2023-07-11 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobileApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order1',
            fields=[
                ('orderId', models.AutoField(primary_key=True, serialize=False)),
                ('orderDate', models.DateField()),
            ],
        ),
    ]
