# Generated by Django 4.2.3 on 2023-07-13 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobileApp1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='terms',
            field=models.CharField(choices=[('CDI', 'CDI'), ('CDD', 'CDD'), ('SESONIER', 'SESONIER'), ('EXTERN', 'EXTERN')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='warehouse',
            name='unity',
            field=models.CharField(choices=[('m3', 'm3'), ('m2', 'm2'), ('PALETTE', 'PALETTE')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='warehouseId',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
