# Generated by Django 4.2.3 on 2023-07-28 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobileApp1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warehouse',
            old_name='capacity',
            new_name='currentCapacity',
        ),
    ]
