# Generated by Django 4.2.3 on 2023-07-28 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobileApp1', '0002_rename_capacity_warehouse_currentcapacity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pointofsale',
            old_name='cashierName',
            new_name='firstName',
        ),
        migrations.AddField(
            model_name='pointofsale',
            name='lastName',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
