# Generated by Django 4.2.3 on 2023-07-28 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobileApp1', '0003_rename_cashiername_pointofsale_firstname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='lastUpdated',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='lastUpdated',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='orderDate',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderTime',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
